connector_image: airbyte/destination-mockapi:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "destination_mockapi/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  basic_write:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        input_path: "integration_tests/messages.jsonl"
